### ISSUE TITLE
Trouble with MIToS import leads here: invalid assignment location "PairwiseListMatrices.t" 

### ISSUE THREAD

**Issue by kool7d** [diegozea/PairwiseListMatrices.jl#13]
I get an error while trying to use MIToS. It says 
```
ERROR: LoadError: LoadError: syntax: invalid assignment location "PairwiseListMatrices.t" around /tmp/jl_goLbod/packages/PairwiseListMatrices/cfFkP/src/pairwiselistmatrix.jl:1040
```
and I am not sure how to fix it.

**Comment by diegozea** [comment]
Hi! Sorry for the late response. I haven't seen it before between the huge amount of messages. The problem is that I am using macros to iterate with custom expressions, as this was designed before anonymous functions were as fast as they are now. And macros can not see the local environment now; this has changed between Julia versions. I will replace those macros with high order functions to solve this problem. Thanks for noticing it, and sorry again for the late response.

**Comment by diegozea** [comment]
Hi! This is finally closed with https://github.com/diegozea/PairwiseListMatrices.jl/commit/24d47c3bccf957bd95b07abdc7eb49f11994f4af. I will tag a new version. Thanks again :)

**Comment by kool7d** [comment]
no problem, my friend!
